"use client";
import { Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { adminRequest } from "@/lib/admin-request";
import type { Team } from "@/types";
import { AdminHeading } from "./admin-shell";
import { EmptyState, SkeletonCards, Toast } from "@/components/ui";

const empty={name:"",institution:"",project_title:""};
export function TeamManager(){const [rows,setRows]=useState<Team[]|null>(null);const [query,setQuery]=useState("");const [editing,setEditing]=useState<Team|null|"new">(null);const [form,setForm]=useState(empty);const [toast,setToast]=useState<{tone:"success"|"error";text:string}|null>(null);
async function load(){const {teams}=await adminRequest<{teams:Team[]}>("/api/admin/teams");setRows(teams)}useEffect(()=>{void adminRequest<{teams:Team[]}>("/api/admin/teams").then(({teams})=>setRows(teams)).catch(error=>{setRows([]);setToast({tone:"error",text:error instanceof Error?error.message:"Unable to load teams."})})},[]);
function open(row?:Team){setEditing(row??"new");setForm(row?{name:row.name,institution:row.institution??"",project_title:row.project_title??""}:empty)}
async function save(event:React.FormEvent){event.preventDefault();try{await adminRequest("/api/admin/teams",{method:editing==="new"?"POST":"PATCH",body:JSON.stringify({...form,institution:form.institution||null,project_title:form.project_title||null,...(editing==="new"?{}:{id:editing!.id})})});setEditing(null);setToast({tone:"success",text:"Team saved successfully."});await load()}catch(error){setToast({tone:"error",text:error instanceof Error?error.message:"Unable to save the team."})}}
async function remove(row:Team){if(!window.confirm(`Delete ${row.name}? All related scores will also be deleted.`))return;try{await adminRequest("/api/admin/teams",{method:"DELETE",body:JSON.stringify({id:row.id})});setToast({tone:"success",text:"Team deleted."});await load()}catch(error){setToast({tone:"error",text:error instanceof Error?error.message:"Unable to delete the team."})}}
const filtered=useMemo(()=>(rows??[]).filter(row=>`${row.name} ${row.institution} ${row.project_title}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);return <><AdminHeading title="Teams" description="Manage competition teams without hardcoding frontend data." action={<button className="button gradient-button" onClick={()=>open()}><Plus size={17}/> Add team</button>}/><label style={{display:"block",position:"relative",marginBottom:16}}><Search size={18} style={{position:"absolute",top:15,left:14,color:"#8b93a5"}}/><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search teams" style={{paddingLeft:42}}/></label>{rows===null?<SkeletonCards/>:filtered.length?<div style={{display:"grid",gap:11}}>{filtered.map(row=><article className="card" key={row.id} style={{padding:18,display:"flex",justifyContent:"space-between",alignItems:"center",gap:15}}><div style={{minWidth:0}}><h2 style={{fontSize:17,margin:"0 0 4px"}}>{row.name}</h2><p className="muted" style={{margin:0,fontSize:12,lineHeight:1.5}}>{[row.institution,row.project_title].filter(Boolean).join(" • ")||"Details not provided"}</p></div><div style={{display:"flex",gap:7}}><button className="button button-secondary" aria-label={`Edit ${row.name}`} onClick={()=>open(row)} style={{paddingInline:13}}><Pencil size={16}/></button><button className="button button-secondary" aria-label={`Delete ${row.name}`} onClick={()=>remove(row)} style={{paddingInline:13,color:"#b42318"}}><Trash2 size={16}/></button></div></article>)}</div>:<EmptyState title="No teams" description="Add the first team to begin judging."/>}{editing&&<Editor title={editing==="new"?"Add team":"Edit team"} form={form} setForm={setForm} close={()=>setEditing(null)} save={save}/>} {toast&&<Toast tone={toast.tone}>{toast.text}</Toast>}</>}
function Editor({title,form,setForm,close,save}:{title:string;form:typeof empty;setForm:React.Dispatch<React.SetStateAction<typeof empty>>;close:()=>void;save:(e:React.FormEvent)=>void}){return <div style={{position:"fixed",zIndex:60,inset:0,background:"rgba(20,25,45,.42)",display:"grid",placeItems:"center",padding:16}}><form onSubmit={save} className="card" style={{width:"min(100%,480px)",padding:24}}><button type="button" aria-label="Close" onClick={close} style={{float:"right",width:44,height:44,border:0,borderRadius:12}}><X size={18}/></button><h2 style={{margin:"8px 0 24px"}}>{title}</h2>{[["Team name","name",true],["Institution","institution",false],["Project title","project_title",false]].map(([label,key,required])=><label key={String(key)} style={{display:"grid",gap:7,fontSize:13,fontWeight:750,marginBottom:13}}>{label}<input className="input" required={Boolean(required)} value={form[key as keyof typeof form]} onChange={e=>setForm(old=>({...old,[String(key)]:e.target.value}))}/></label>)}<button className="button gradient-button" style={{width:"100%",marginTop:8}}>Save team</button></form></div>}
